version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./target/financeiroBank-0.0.1-SNAPSHOT.jar:/app/financeiroBank.jar
    ports:
      - "8080:8080"
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-west-2

networks:
  default:
    name: financeirobank_default
